<?php
  define('ACTION_OK', 1);
  define('ACTION_FAILED', 2);
  define('SERVER_ERROR', 3);

  define('FORM_DATA_MISSING', 4);
  define('WRONG_PASSWORD', 5);
  define('PASSWORDS_DO_NOT_MATCH', 6);

  define('INVALID_ID', 7);
  define('USER_NAME_ALREADY_EXISTS', 8);

  define('USERNAME_LENGTH_ERROR', 9);
  define('PASSWORD_LENGTH_ERROR', 10);
  
  define('LOGIN_REQUIRED', 11);
  define('NO_CAPTCHA', 12);
  
  define('CATEGORY_NAME_ALREADY_EXISTS', 13);
  define('CATEGORY_NAME_WAS_NOT_CHANGED', 14);
  
  define('CATEGORY_POSITIONS_ARE_NOT_UNIQUE', 15);
  
  define('CATEGORY_NAME_WAS_CHANGED_AND_LIMIT_WAS_SET', 16);
  define('CATEGORY_NAME_WAS_CHANGED_AND_LIMIT_COULD_NOT_BE_CHANGED', 17);
  define('CATEGORY_NAME_WAS_CHANGED_AND_LIMIT_HAS_BEEN_REMOVED', 18);
  define('CATEGORY_NAME_WAS_CHANGED_AND_LIMIT_HAS_REMAINED_UNCHANGED', 19);
  
  define('CATEGORY_NAME_COULD_NOT_BE_CHANGED_AND_LIMIT_WAS_SET', 20);
  define('CATEGORY_NAME_COULD_NOT_BE_CHANGED_AND_LIMIT_COULD_NOT_BE_CHANGED', 21);
  define('CATEGORY_NAME_COULD_NOT_BE_CHANGED_AND_LIMIT_HAS_BEEN_REMOVED', 22);
  define('CATEGORY_NAME_COULD_NOT_BE_CHANGED_AND_LIMIT_HAS_REMAINED_UNCHANGED', 23);
  
  define('CATEGORY_NAME_ALREADY_EXISTS_AND_LIMIT_WAS_SET', 24);
  define('CATEGORY_NAME_ALREADY_EXISTS_AND_LIMIT_COULD_NOT_BE_CHANGED', 25);
  define('CATEGORY_NAME_ALREADY_EXISTS_AND_LIMIT_HAS_BEEN_REMOVED', 26);
  define('CATEGORY_NAME_ALREADY_EXISTS_AND_LIMIT_HAS_REMAINED_UNCHANGED', 27);
  
  define('CATEGORY_NAME_HAS_REMAINED_UNCHANGED_AND_LIMIT_WAS_SET', 28);
  define('CATEGORY_NAME_HAS_REMAINED_UNCHANGED_AND_LIMIT_COULD_NOT_BE_CHANGED', 29);
  define('CATEGORY_NAME_HAS_REMAINED_UNCHANGED_AND_LIMIT_HAS_BEEN_REMOVED', 30);
  define('CATEGORY_NAME_HAS_REMAINED_UNCHANGED_AND_LIMIT_HAS_REMAINED_UNCHANGED', 31);
  
  define('CATEGORY_NAME_WAS_CHANGED_AND_LIMIT_AMOUNT_IS_NOT_VALID', 32);
  define('CATEGORY_NAME_COULD_NOT_BE_CHANGED_AND_LIMIT_AMOUNT_IS_NOT_VALID', 33);
  define('CATEGORY_NAME_ALREADY_EXISTS_AND_LIMIT_AMOUNT_IS_NOT_VALID', 34);
  define('CATEGORY_NAME_HAS_REMAINED_UNCHANGED_AND_LIMIT_AMOUNT_IS_NOT_VALID', 35);
  
?>